### ISSUE TITLE
delay.h: No such file or directory

### ISSUE THREAD

**Issue by max5555** [Duckle29/tiny_sht4x#1]
I've got the following error during compilation for espressif 32

`.pio\libdeps\esp32dev\tiny_sht4x\src\sht4x.h:3:24: fatal error: util/delay.h: No such file or directory`

Here is my platformio.ini

```
[platformio]
default_envs = esp32dev

[env]
upload_speed = 921600
monitor_speed = 115200
lib_ldf_mode = deep+
lib_compat_mode = strict

lib_deps =
    duckle/tiny_sht4x @ ^1.0.3
```

**Comment by Duckle29** [comment]
Hi there

Thanks for taking the time to open an issue! :D

Should be fixed in 0f04da785feb8b63bad28e6b397874c47d560ceb which is pushed to pio registry as 1.0.4 :smiley: 

I haven't tested if this actually works on an esp32 or 8266, so if you have confirmation it does I'd love to hear it :) (and also if it doesn't ;) )
